# Generated by Django 6.0.4 on 2026-04-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProdutoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("precoCusto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precoVenda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantidade_estoque", models.IntegerField()),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "produtos",
                "ordering": ["nome"],
            },
        ),
    ]
